version: '3'

services:
  php:
    image: marjamenge/docker-php5.3-apache2.2
    container_name: ${CONTAINER_PREFIX}.php
    volumes:
        - ./www:/var/www/html
        - ./apachelogs:/var/log/apache2
        - ./apache2conf:/etc/apache2/sites-available
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - ${WWW_PORT}:8088
    links:
        - mysql
    networks:
        static-network:
            ipv4_address: 172.16.238.11
  phpmyadmin:
    image: dnhsoft/phpmyadmin:4.0.10.9
    container_name: ${CONTAINER_PREFIX}.phpmyadmin
    ports:
        - ${PHPMYAMDIN_PORT}:80
    links:
        - mysql
    environment:
        - DBHOST=mysql
        - DBUSER=${MYSQL_USER}
        - DBPASS=${MYSQL_PASSWORD}
    networks:
        static-network:
            ipv4_address: 172.16.238.12
  mysql:
    image: mysql:5.5
    container_name: ${CONTAINER_PREFIX}.mysql
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf.d:/etc/mysql/conf.d
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - ${MYSQL_PORT}:3306
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
        static-network:
            ipv4_address: 172.16.238.13

networks:
    static-network:
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24