version: '3'

services:
  php:
    build: ./php
    container_name: ${CONTAINER_PREFIX}.php
    volumes:
        - ./www:/var/www/html
        - ./logs:/var/log/apache2
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - ${WWW_PORT}:8088
    links:
        - mysql
  phpmyadmin:
    image: dnhsoft/phpmyadmin:4.0.10.9
    container_name: ${CONTAINER_PREFIX}.phpmyadmin
    ports:
        - ${PHPMYAMDIN_PORT}:80
    links:
        - mysql
    environment:
        - DBHOST=mysql
        - DBUSER=${MYSQL_USER}
        - DBPASS=${MYSQL_PASSWORD}
  mysql:
    image: mysql:5.5
    container_name: ${CONTAINER_PREFIX}.mysql
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf.d:/etc/mysql/conf.d
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - ${MYSQL_PORT}:3306
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}